resteasy:
  jaxrs:
    app:
      registration: property
      classes: com.example.sb.log4j2.rest.config.JakartaWsConfiguration
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - shutdown
          - loggers
  endpoint:
    loggers:
      access: unrestricted
    shutdown:
      access: read_only
logging:
  level:
    com:
      example:
        sb:
          log4j2: info
    org:
      springframework: info
      jboss:
        resteasy: info