resteasy:
  jaxrs:
    app:
      registration: property
      classes: com.example.jakarta_resteasy.rest.config.JakartaWsConfiguration
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - shutdown
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    com:
      example:
        jakarta_resteasy:
          rest:
            service: debug
    org:
      springframework: info
      jboss:
        resteasy: info