app:
  topic-name: "dev-topic"
spring:
  application:
    name: "test-dev-producer" # used to generate a producer name
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    com:
      example:
        sb:
          kafka: info
    org:
      springframework: info
      jboss:
        resteasy: info
