resteasy:
  jaxrs:
    app:
      registration: property
      classes: com.example.jaxrs_resteasy.rest.config.JaxRsConfiguration
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - shutdown
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    org:
      springframework: info
      jboss:
        resteasy: info